### ISSUE TITLE
Quadruple precision

### ISSUE THREAD

**Issue by sudhanvalalit** [starkiller-astro/XNet#3]
I tried to convert the code from double precision to quadruple precision, and the code compiles well. However, while execution, it fails to read nets3 and nets4 files. Is there a proper way to read/write binary datafiles in quadruple precision?

At line 621 of file xnet_data.f90
Fortran runtime error: I/O past end of record on unformatted file

Error termination. Backtrace:
#0  0x7f6c94688d59 in read_block_direct
at /usr/src/debug/gcc/gcc/libgfortran/io/transfer.c:789
#1  0x7f6c94688d59 in unformatted_read
at /usr/src/debug/gcc/gcc/libgfortran/io/transfer.c:1129
#2  0x55f18526bc8e in __reaction_data_MOD_read_reaction_data
at /home/sudhanvalalit/Documents/XNet/src/xnet_data.f90:621
#3  0x55f18535e081 in net
at /home/sudhanvalalit/Documents/XNet/src/net.f90:109
#4  0x55f18525449e in main
at /home/sudhanvalalit/Documents/XNet/src/net.f90:18

**Comment by jaharris87** [comment]
Your best bet is probably to read/write nets3 and nets4 as double precision and then convert to quad.
I don't know how well quad-precision is supported by Fortran I/O.

**Comment by sudhanvalalit** [comment]
Thanks for a quick response, let me try that and get back to you.
